export {
  GET_USER_PROFILES_QUERY,
  GET_USER_PROFILE_QUERY,
  GET_ALL_GROUPS_QUERY,
  GET_ALL_LOCATIONS_QUERY,
  GET_ALL_MANAGERS_QUERY,
} from './user_profiles/queries';

export {
  DELETE_USER_PROFILE_MUTATION,
  UPDATE_USER_PROFILE_MUTATION,
  SEND_NEW_CREDENTIALS_MUTATION,
  CREATE_NEW_USER_MUTATION,
} from './user_profiles/mutations';

export {
  GET_ALL_DATA_CENTERS,
  GET_DATA_CENTER,
  GET_ALL_CORE_SWITCHES,
  GET_ALL_OLT,
  GET_OLT,
  GET_ALL_FDT,
  GET_ALL_FDT_SPLITTER,
  GET_ODB,
  GET_ALL_FDT_ODB,
  GET_ALL_CPE,
  GET_FDT,
  GET_ALL_DC_LOCATIONS,
  GET_ALL_OLT_SLOTS,
  GET_ALL_OLT_PORTS,
  GET_CORE_SW_VLAN,
  GET_CORE_SWITCH,
  GET_CORE_SWITCH_SLOT,
  GET_ALL_CORE_SWITCH_SLOTS,
  GET_CORE_SWITCH_PORT,
  GET_ALL_CORE_SWITCH_PORTS,
  GET_ALL_FDT_SPLITTER_PORTS,
  GET_FDT_SPLITTER,
  GET_OLT_SLOT,
  GET_OLT_PORT,
} from './asset_management/queries';

export {
  ADD_NEW_DATA_CENTER_MUTATION,
  UPDATE_NEW_DATA_CENTER_MUTATION,
  DELETE_DATA_CENTER_MUTATION,
  ADD_NEW_CORE_SWITCH_MUTATION,
  UPDATE_CORE_SWITCH_MUTATION,
  DELETE_CORE_SWITCH_MUTATION,
  ADD_NEW_OLT_MUTATION,
  DELETE_OLT_MUTATION,
  ADD_NEW_FDT_MUTATION,
  UPDATE_FDT_SPLITTER,
  DELETE_FDT_MUTATION,
  ADD_NEW_FDT_SPLITTER_MUTATION,
  DELETE_FDT_SPLITTER_MUTATION,
  ADD_NEW_CPE_MUTATION,
  DELETE_CPE_MUTATION,
  UPDATE_FDT,
  ADD_NEW_CORE_SWITCH_SLOT_MUTATION,
  DELETE_CORE_SWITCH_SLOTS_MUTATION,
  ADD_NEW_CORE_SWITCH_PORT_MUTATION,
  ADD_NEW_OLT_PORT_MUTATION,
  UPDATE_CORE_SWITCH_SLOT,
  UPDATE_CORE_SWITCH_PORT,
  ADD_NEW_ODB_MUTATION,
  ADD_NEW_OLT_SLOT_MUTATION,
  CREATE_CORE_CW_VLAN,
  UPDATE_ODB_MUATION,
  DELETE_CORE_SWITCH_PORTS_MUTATION,
  UPDATE_OLT,
  UPDATE_OLT_SLOT,
  UPDATE_OLT_PORT,
} from './asset_management/mutations';

export { GET_ALL_SERVICE_CATALOG, GET_SERVICE_CATALOG,GET_CONNECTION_TYPES } from './b2b_catalog/queries';
export { UPDATE_SERVICE_CATALOG, CREATE_SERVICE_CATALOG, DELETE_SERVICE_CATALOG_ITEM } from './b2b_catalog/mutations';

export { GET_ALL_SERVICE_SUBSCRIPTIONS, GET_SERVICE_SUBSCRIPTIONS } from './b2b_subscriptions/queries';
export {
  DELETE_B2B_CATALOG_SUBSCRIPTIONS,
  UPDATE_CATALOG_SUBSCRIPTIONS,
  CREATE_CATALOG_SUBSCRIPTIONS,
} from './b2b_subscriptions/mutations';
