export { DELETE_USER_PROFILES_SERVICE, GET_GROUPS_SERVICE } from './user_profiles';
export {
  DELETE_DATA_CENTER_SERVICE,
  DELETE_CORE_SWITCH_SERVICE,
  DELETE_OLT_SERVICE,
  DELETE_FDT_SERVICE,
  DELETE_FDT_SPLITTER_SERVICE,
  DELETE_CPE_SERVICE,
  DELETE_CORE_SWITCH_SLOTS_SERVICE,
} from './asset_management';
export { DELETE_B2B_CATALOG_ITEM_SERVICE } from './b2b_catalog';
export { DELETE_B2B_CATALOG_SUBSCRIPTIONS_SERVICE } from './b2b_subscriptions';
